title: "Foco Acessível" 
description: "Foco Acessível: conversas inspiradoras e informativas sobre acessibilidade e inclusão com uso da tecnologia. Junte-se a nós!"
tagline : Um podcast sobre acessibilidade, inclusãodiversidade e tecnologia.
permalink: /:categories/:title
url: 'https://focoacessivel.com.br'

footer-description: <p>Espaço dedicado à promoção da acessibilidade, diversidade e inclusão na tecnologia, com a participação de profissionais que compartilham suas vivências, desafios e conquistas.</p><p>Neste podcast, queremos inspirar você a contribuir para um mundo mais acessível e inclusivo para todas as pessoas.</p>

email: focoacessivel@gmail.com
disqus_shortname: foco-acessivel

author: Wagner Beethoven
author-picture: 'http://sumo.pe/img/avatar.jpg'
author-alt: 'Foto de homem de pele branca, cabelos e barba curta e preta, usa óculos, sorri, veste camisa vermelha'
banner: 'img/banner.png'
image: 'img/banner.png'
logo: '/img/logo.svg'
logo-alt: Do lado esquerdo dois círculos um maior e outro menor, estão centralizados um dentro do outro. O maior é tracejado e não é preenchido com cor e o menor é preenchido com cor. Ao lado das formas, o texto 'Foco Acessível'. A logo está apresentada na cor verde escuro.
icone-alt: Dois círculos um maior e outro menor, estão centralizados um dentro do outro. O maior é tracejado e não é preenchido com cor e o menor é preenchido com cor.

twitter:
  username: focoacessivel
  card: summary_large_image

facebook:
  # app_id: 1234
  publisher: 111914578444788  # page
  admins: 10161123949632868   # profile

social:
  name: Wagner Beethoven
  links:
    - https://twitter.com/wagnerbeethoven
    - https://www.facebook.com/wagnerbeethoven
    - https://www.linkedin.com/in/wagnerbeethoven
    - https://github.com/wagnerbeethoven
    - https://behance.net/wagnerbeethoven
    - https://wagnerbeethoven.medium.com/

locale: pt-BR

webmaster_verifications:
  google: 7-Sd29Rki1XiyKpJpJprXYqISN18fWrbioJ9-SheyC0
  bing: 0CA3CBC6739B201C0C6101FDC414E75B

sass:
  style: compressed
  sass_dir: _sass
  cache: 'true'


compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

brotli:
  extensions:
    - '.html'
    - '.css'
    - '.js'

plugins:
  - jekyll-feed
  - jekyll-brotli
  - jekyll-seo-tag
  - jekyll-sitemap
