title: "Foco Acessível" 
description: "Foco Acessível: conversas inspiradoras e informativas sobre acessibilidade e inclusão com uso da tecnologia. Junte-se a nós!"
description-short: Podcast com profissionais de tecnologia e acessibilidade


site.banner: 'img/banner.png'

permalink: /:categories/:title

email: focoacessivel@gmail.com
disqus_shortname: foco-acessivel

compress_html:
  clippings: []
  comments: []
  endings: []
  profile: false
  blanklines: false
  ignore:
    envs: []

plugins:
  - jekyll-feed
  - jekyll-brotli
