title: "Foco Acessível" 
description: "O FOco Acessível tem o objetivo de criar uma conversa significativa e informativa sobre acessibilidade e inclusão, e esperamos inspirar e informar nossos ouvintes sobre como a tecnologia pode ser usada para construir uma sociedade mais acessível e inclusiva."
permalink: /:categories/:title
email: focoacessivel@gmail.com

compress_html:
  clippings: []
  comments: []
  endings: []
  profile: false
  blanklines: false
  ignore:
    envs: []

plugins:
  - jekyll-feed
  - jekyll-brotli
